# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pw5_1Sm4Qox-py6m2I3pQShkl2cwjKT
"""

!pip install transformers gTTS moviepy
from transformers import pipeline, set_seed
from gtts import gTTS
from IPython.display import Audio
from google.colab import files
from moviepy.editor import *
import os

generator = pipeline("text-generation", model="gpt2")
set_seed(42)


genre = input("Enter a genre (Fantasy / Mystery / Sci-Fi / Horror): ")
prompt = input("Enter the beginning of your story: ")


full_prompt = f"{genre} story: {prompt}"


story = generator(full_prompt, max_length=200, num_return_sequences=1)
generated_story = story[0]['generated_text']


print("\n📝 Generated Story:\n")
print(generated_story)


tts = gTTS(generated_story, lang='en')


audio_filename = "story_audio.mp3"
tts.save(audio_filename)
print("Audio saved as story_audio.mp3")

Audio(audio_filename)

print("Please upload a background image for the video (JPG or PNG)")
uploaded = files.upload()


image_filename = list(uploaded.keys())[0]
print(f" Using image: {image_filename}")

image_clip = ImageClip(image_filename, duration=30)  # 30 seconds
audio_clip = AudioFileClip(audio_filename)


video_clip = image_clip.set_audio(audio_clip)


video_clip = video_clip.resize(height=720)
video_clip = video_clip.set_fps(24)

video_filename = "story_video.mp4"
video_clip.write_videofile(video_filename, codec="libx264", audio_codec="aac")

files.download(video_filename)